### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by miharekar** [planetruby/conferences#6]
I think https://github.com/planetruby/awesome-events/commit/7ed70d139f8e2b51bede9d4b952117bda93b44e9 broke the links.

For example - you link to https://github.com/planetruby/awesome-events#slovenia but the link should be https://github.com/planetruby/awesome-events#slovenia-si

**Comment by geraldb** [comment]
Good point. Thanks. Will fix it now. Changed the country heading (now includes the internet domain.). Cheers.

**Comment by miharekar** [comment]
Awesome! And thanks for including @RubySlovenia from the get-go :smile: :+1:

**Comment by geraldb** [comment]
You're welcome. All fixed now. Cheers.
