### ISSUE TITLE
Conferences in 2022?

### ISSUE THREAD

**Issue by AndyObtiva** [planetruby/conferences#74]
Hi,

Any chance we'd get this updated for 2022?

Examples:

- https://www.sincityruby.com/ (USA)
- https://www.oregoncc.org/en/events/2022/05/railsconf-2022 (USA)
- https://west.railscamp.us/2022 (USA)
- https://2022.euruko.org/ (Finland)

I don't know any more conferences. I was hoping you do.

**Comment by geraldb** [comment]
Happy New Year 2022! Prosit 2022!

As always thanks for your contributions and keeping planet ruby alive with some updates   I added a new 2022 datafile - see <https://github.com/planetruby/conferences/blob/master/_data/conferences2022.yml> with  your listed conferences - you are welcome to add more  (by adding to the datafile).  The feed.xml and feed.json is changed over to 2022 and the  2022 page is live at <https://planetruby.github.io/conferences/2022>.   Cheers. Prost.
